### ISSUE TITLE
스타일 관리 라이브러리를 사용하는 건 어떨까요?

### ISSUE THREAD

**Issue by Kihyun92** [doddlex2/WYI#4]
[styled component](https://styled-components.com/)나 다른 스타일 라이브러리들을 사용해도 좋을 것 같아요.

cc. @dodohyun0807

**Comment by dodohyun0807** [comment]
CSS는 놔두고 Quiz page 작업 들어가볼게요

**Comment by Kihyun92** [comment]
styled-component 사용할 예정임
